name: Push a new tag with minor update

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest 
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
       
      - name: GitHub Tag Name example
        run: |
          echo "${{ steps.get-latest-tag.outputs.tag }}"

      - id: step1
        if: ${{ steps.get-latest-tag.outputs.tag == 'v0.0.0' }}
        uses: actions-ecosystem/action-push-tag@v1
        with:
            tag: "v1.0.1-RC"
            message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
      - id: step2
        if: ${{ steps.get-latest-tag.outputs.tag != 'v0.0.0' }}
        uses: actions-ecosystem/action-push-tag@v1
        with:
            tag: "v1.0.2-RC"
            message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
      - name: Print Values
        run: |
          echo "${{ step1.tag }}"
          echo "${{ step2.tag }}"
       
